module Flaggy
class ProteinSource
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_features.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "get_features.Request" do
    optional :app, :string, 1
  end
  add_message "get_features.Response" do
    optional :features, :string, 1
  end
end

module GetFeatures
  Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("get_features.Request").msgclass
  Response = Google::Protobuf::DescriptorPool.generated_pool.lookup("get_features.Response").msgclass
end
end
end
